### PR TITLE
One fix, and several tweaks for RetrieveSymbols

### PR DESCRIPTION
**Pull request by ariccio**
The most important part is that I've fixed a buffer overrun in RetrieveSymbols (90bbf6c249d7f6b387c4b4526c1d62d79a3bdfae) that was the result of passing a buffer to SymFindFileInPath that was too small.

I also fixed the inconsistent line endings (101fbc086ab3720cd3f520b1184540938a1e229a), and turned the warnings up / `/analyze` on (402d5892cf4a9821312e41d45327bd075be79f3f).

### CODE REVIEW

**Comment by randomascii** [comment]
The problem with fixing line endings and other changes simultaneously is it becomes impossible to see what the changes are (well, inconvenient). Consider separating the changes to make them all visible?

But I saw the buffer size change. I'm confused by it. The documentation for that parameter says "FilePath [out]
A pointer to a buffer that receives the fully qualified path to the symbol file. This buffer must be at least MAX_PATH characters." I've never seen a need for a MAX_PATH+1 sized buffer. What up?

**Comment by randomascii** [comment]
Ah. I see the warning. That is messed up. I have complained to the authorities.

Who to trust...

I'm not sure there any null-termination guarantees either, so that's annoying.

**Comment by randomascii** [comment]
Anyway, best to be safe I guess. The changes all seem good (I think). If you can split them into two changes so that the code changes are visible them I'll happily accept them. I can investigate whether the docs or headers are correct some other day. Thanks for finding the warning/possible-bug.

**Comment by ariccio** [comment]
> The problem with fixing line endings and other changes simultaneously is it becomes impossible to see what the changes are (well, inconvenient). Consider separating the changes to make them all visible?

Good point. I might need to use some `git cherry-pick` magic.



> A pointer to a buffer that receives the fully qualified path to the symbol file. This buffer must be at least MAX_PATH characters." I've never seen a need for a MAX_PATH+1 sized buffer. What up?

[...]

> Who to trust...

Well, anytime someone uses `MAX_PATH` as the size of a buffer intended to hold *an entire file path*, you should be *very* suspicious. That's the wrong interpretation of what `MAX_PATH`' actually represents. `MAX_PATH` means 'the maximum length of a single file path component`, and shouldn't really be used as the size of a buffer for a file path.

Of course, most paths are actually *shorter* than `MAX_PATH`, so they seem to work correctly, and thus the problem persists until the codebase *depends* on that behavior. This is the reason why I wrote the `isValidPathToFsObject` function (and friends) in that 'test' branch, so that we'd have a generalized way of avoiding this mistake from the beginning.

**Comment by ariccio** [comment]
....well that's weird


Here's the console session that corresponds to the duplicated commits:

```
AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (master)
$ git status
On branch retrieve-symbols-tweaks-n-fixes
Your branch is up-to-date with 'origin/retrieve-symbols-tweaks-n-fixes'.

nothing to commit, working directory clean

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: fix line endings
Applying: tweaked project settings
Applying: enabled "treat linker warnings as errors"
Applying: small tweaks, fixed a buffer overrun
Applying: turned on /Gw

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
$ git status
On branch retrieve-symbols-tweaks-n-fixes
Your branch and 'origin/retrieve-symbols-tweaks-n-fixes' have diverged,
and have 52 and 5 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working directory clean

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
$ git pull --verbose
From https://github.com/ariccio/UIforETW
 = [up to date]      retrieve-symbols-tweaks-n-fixes -> origin/retrieve-symbols-tweaks-n-fixes
 = [up to date]      debugging-python-handle-issues-nonfunctional-branch -> origin/debugging-python-handle-issues-nonfunctional-branch
 = [up to date]      development-branch -> origin/development-branch
 = [up to date]      master     -> origin/master
 = [up to date]      strip-chrome-symbols-refactor-into-smaller-funcs -> origin/strip-chrome-symbols-refactor-into-smaller-funcs
Merge made by the 'recursive' strategy.

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
$ git status
On branch retrieve-symbols-tweaks-n-fixes
Your branch is ahead of 'origin/retrieve-symbols-tweaks-n-fixes' by 53 commits.
  (use "git push" to publish your local commits)

nothing to commit, working directory clean

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
$ git push --verbose
Pushing to https://github.com/ariccio/UIforETW.git
Counting objects: 30, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (19/19), done.
Writing objects: 100% (19/19), 2.02 KiB | 0 bytes/s, done.
Total 19 (delta 14), reused 0 (delta 0)
POST git-receive-pack (2252 bytes)
To https://github.com/ariccio/UIforETW.git
   1de3887..8ada819  retrieve-symbols-tweaks-n-fixes -> retrieve-symbols-tweaks-n-fixes
updating local tracking ref 'refs/remotes/origin/retrieve-symbols-tweaks-n-fixes'

AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
$
```

Did I do something obviously wrong?

**Comment by randomascii** [comment]
Amazingly enough MAX_PATH does actually refer to the total path length. If
you keep creating nested directories then eventually Windows will tell you
that you can't. I tested this last week when this came up and while I
didn't hit exactly MAX_PATH as a limit (I think dbghelp.dll was creating an
intermediate file that was slightly longer) I got very close, despite each
component being only about twenty characters. There is a different syntax
(something like \\?\\device0 instead of c:\) that lets you break past
MAX_PATH, but for normal paths it is a hard limit. Some people have hit
this where they rip their music collection (which includes deeply nested
and long album/artist/song names) and all is well until they copy them to a
machine where somebody has a longer user name and 1% of the files fail to
copy. It's awesome. Anyway...

I don't understand why git sometimes puts the local commits at the
beginning and sometimes at the end. I thought you must be doing something
weird, but then I hit the same thing myself. It's annoying. But it doesn't
always happen, so there is some weird heuristic going on. I'll figure it
out and get that pull request merged in tonight, if I can.

On Thu, May 21, 2015 at 7:35 PM, Alexander Riccio <notifications@github.com>
wrote:

> ....well that's weird
>
> Here's the console session that corresponds to the duplicated commits:
>
> AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (master)
> $ git status
> On branch retrieve-symbols-tweaks-n-fixes
> Your branch is up-to-date with 'origin/retrieve-symbols-tweaks-n-fixes'.
>
> nothing to commit, working directory clean
>
> AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
> $ git rebase master
> First, rewinding head to replay your work on top of it...
> Applying: fix line endings
> Applying: tweaked project settings
> Applying: enabled "treat linker warnings as errors"
> Applying: small tweaks, fixed a buffer overrun
> Applying: turned on /Gw
>
> AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
> $ git status
> On branch retrieve-symbols-tweaks-n-fixes
> Your branch and 'origin/retrieve-symbols-tweaks-n-fixes' have diverged,
> and have 52 and 5 different commits each, respectively.
>   (use "git pull" to merge the remote branch into yours)
>
> nothing to commit, working directory clean
>
> AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
> $ git pull --verbose
> From https://github.com/ariccio/UIforETW
>  = [up to date]      retrieve-symbols-tweaks-n-fixes -> origin/retrieve-symbols-tweaks-n-fixes
>  = [up to date]      debugging-python-handle-issues-nonfunctional-branch -> origin/debugging-python-handle-issues-nonfunctional-branch
>  = [up to date]      development-branch -> origin/development-branch
>  = [up to date]      master     -> origin/master
>  = [up to date]      strip-chrome-symbols-refactor-into-smaller-funcs -> origin/strip-chrome-symbols-refactor-into-smaller-funcs
> Merge made by the 'recursive' strategy.
>
> AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
> $ git status
> On branch retrieve-symbols-tweaks-n-fixes
> Your branch is ahead of 'origin/retrieve-symbols-tweaks-n-fixes' by 53 commits.
>   (use "git push" to publish your local commits)
>
> nothing to commit, working directory clean
>
> AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
> $ git push --verbose
> Pushing to https://github.com/ariccio/UIforETW.git
> Counting objects: 30, done.
> Delta compression using up to 8 threads.
> Compressing objects: 100% (19/19), done.
> Writing objects: 100% (19/19), 2.02 KiB | 0 bytes/s, done.
> Total 19 (delta 14), reused 0 (delta 0)
> POST git-receive-pack (2252 bytes)
> To https://github.com/ariccio/UIforETW.git
>    1de3887..8ada819  retrieve-symbols-tweaks-n-fixes -> retrieve-symbols-tweaks-n-fixes
> updating local tracking ref 'refs/remotes/origin/retrieve-symbols-tweaks-n-fixes'
>
> AlexanderRiccio@ALEXANDERLAPTOP ~/Documents/GitHub/UIforETW (retrieve-symbols-tweaks-n-fixes)
> $
>
> Did I do something obviously wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/UIforETW/pull/34#issuecomment-104479376>.
>



-- 
Bruce Dawson

**Comment by ariccio** [comment]
> Amazingly enough MAX_PATH does actually refer to the total path length. If you keep creating nested directories then eventually Windows will tell you that you can't. 

Nope. That's just Windows Explorer, which also mistakenly uses `MAX_PATH` as the maximum path length.

If you do `fsutil fsinfo volumeinfo` on an NTFS volume, you'll see that it explicitly mentions the "component" length.


The authoritative document: ["Naming Files, Paths, and Namespaces
"](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247.aspx), is poorly worded (and thus easy to misread), but mentions a difference between API limitations ("In the Windows API") and kernel object manager/NTFS limits, whereby the limit of a *total* path length is *roughly* 32,767 characters.

**Comment by randomascii** [comment]
So, here's what I did. I did the command-line process of creating a branch and merging this in. There were some conflicts from the line-ending change (sigh) but those were trivial to resolve. I then fixed one more warning and added to your comment. All good.

Then I did a merge --squash to bring it into the main line in one change instead of a dozen. That meant I had to troll through the history to get all of your notes, but that's not a big deal. The end result is much cleaner.

I think I'll do this process in the past. If you want control over the final commit message then you can do the merge --squash/git add/write-your-own-commit-message dance yourself. Either way.

**Comment by randomascii** [comment]
I just tried fsutil and it does list a maximum component length. Notice that it is 255 - unrelated to MAX_PATH.

I agree that MAX_PATH is an API limitation. And the APIs that we are using have that limitation, so as written UIforETW has a MAX_PATH limitation. Or something like that. Certainly the limitation is more pervasive than explorer, but I'm not totally clear on the details. If nothing else cmd.exe has the limitation, and so does SymFindFileInPath. I think you can indicate to most or all of these APIs that you want longer paths with the \\?\\ prefix, but I'm vague on the details. Uggh.

Anyway, change landed.

**Comment by ariccio** [comment]
...and yes, it IS pathetic that a core system component suffers from such a basic mistake.

**Comment by ariccio** [comment]
> I think I'll do this process in the past. 

*In the past??!?* You must have that [new time machine from research](http://blogs.msdn.com/b/oldnewthing/archive/2015/04/02/10604694.aspx).

**Comment by randomascii** [comment]
I've said too much already.

On Thu, May 21, 2015 at 10:10 PM, Alexander Riccio <notifications@github.com
> wrote:

> I think I'll do this process in the past.
>
> *In the past??!?* You must have that new time machine from research
> <http://blogs.msdn.com/b/oldnewthing/archive/2015/04/02/10604694.aspx>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/UIforETW/pull/34#issuecomment-104512315>.
>



-- 
Bruce Dawson

**Pull request closed without merging**
