### PR TITLE
Add stricter code analysis rules

### PR DESCRIPTION
**Pull request by ariccio**
Description copied from commit message for d4f69ade9c4615bdaceb00fa53b78281a7d71e88:

> [this patch makes] Many `/analyze` warnings that are ALMOST ALWAYS actual bugs now cause the build to fail!

> This makes it impossible to miss them as the code analysis warning pops up/disappears, and thus also prevents hitting F5 from starting a built project if there are warnings.

> That last scenario, hitting F5 (triggering a rebuild) and running the resulting program (despite the `/analyze` warnings) has been annoying for me before, because /analyze warnings do not otherwise cause failure (even) when [/WX](https://msdn.microsoft.com/en-us/library/thxezb7y.aspx) is enabled.

Of course, code analysis warnings [should be](https://connect.microsoft.com/VisualStudio/feedback/details/799873/detection-of-variable-shadowing-should-be-part-of-the-regular-c-compile-instead-of-analyze) [part of the normal compiler warnings](https://connect.microsoft.com/VisualStudio/Feedback/Details/799869), but that's not the case in VS2013.

### CODE REVIEW

**Comment by randomascii** [comment]
> Of course, code analysis warnings should be part of the normal compiler warnings

Well, to be fair, having all code analysis warnings as part of the normal compile is not practical, because some code analysis warnings require deep analysis that can slow down the compile, or have high false-positive rates. But yes, some warnings should be available in the regular builds.

**Comment by randomascii** [comment]
Merged. The code analysis slows down building enough that I may end up disabling it. We'll see. Also, on release builds there are two warnings and I'm not sure how to handle them. If SHGetKnownFolderPath fails then there isn't much we can do except exit anyway. Sigh...

Here are the warnings:

uiforetw\uiforetw\uiforetwdlg.cpp(299): warning C6102: Using 'windowsDir' from failed function call at line '298'.
uiforetw\uiforetw\uiforetwdlg.cpp(310): warning C6102: Using 'progFilesx86Dir' from failed function call at line '309'.

**Comment by ariccio** [comment]
> The code analysis slows down building enough that I may end up disabling it

Huh?? I barely notice it - what's typical for you? What's /Bt+ say? /time?


> on release builds there are two warnings

I'm doubly confused...I don't remember seeing any warnings??

**Comment by ariccio** [comment]
I'm feeling very picky. `/Bt+`, and `/time`.

**Comment by randomascii** [comment]
The warnings are release only (I think), so check the Release builds. A different VERIFY macro could resolve them.

As for the times, I enabled build timing to give me a total, which makes for an easier comparison (Tools-> Options-> Projects and Solutions-> VC++ Project Settings-> Build Timing). The total clean-build time with code analysis is 41.208 s for a release build. The total time without code analysis is 8.097 s, so ~5x faster. I've pasted the two timing results in below. The results would be different for debug builds and for incremental builds, but /analyze is always slower. This is more or less by design.

1>------ Build started: Project: UIforETW, Configuration: Release Win32 ------
1>  stdafx.cpp
1>  _WIN32_WINNT not defined. Defaulting to _WIN32_WINNT_MAXVER (see WinSDKVer.h)
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=2.76849s < 745234333500 - 745241885393 > BB [D:\src\UIforETW\UIforETW\stdafx.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xxast.dll)=24.00984s < 745241898068 - 745307392164 > BB [D:\src\UIforETW\UIforETW\stdafx.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.09896s < 745307399794 - 745307669733 > BB [D:\src\UIforETW\UIforETW\stdafx.cpp]
1>  ChildProcess.cpp
1>  DirectoryMonitor.cpp
1>  KeyLoggerThread.cpp
1>  Settings.cpp
1>  Support.cpp
1>  Utility.cpp
1>  UIforETW.cpp
1>  UIforETWDlg.cpp
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.48632s < 745309151300 - 745310477885 > BB [D:\src\UIforETW\UIforETW\KeyLoggerThread.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.59031s < 745309150612 - 745310760862 > BB [D:\src\UIforETW\UIforETW\DirectoryMonitor.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.63977s < 745309136877 - 745310882048 > BB [D:\src\UIforETW\UIforETW\ChildProcess.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.64105s < 745309158029 - 745310906673 > BB [D:\src\UIforETW\UIforETW\Settings.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.63280s < 745309213166 - 745310939332 > BB [D:\src\UIforETW\UIforETW\Support.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.64322s < 745309218795 - 745310973379 > BB [D:\src\UIforETW\UIforETW\UIforETW.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.72078s < 745309215204 - 745311181357 > BB [D:\src\UIforETW\UIforETW\Utility.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.97686s < 745309219843 - 745311884513 > BB [D:\src\UIforETW\UIforETW\UIforETWDlg.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xxast.dll)=1.88717s < 745310491331 - 745315639145 > BB [D:\src\UIforETW\UIforETW\KeyLoggerThread.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.01694s < 745315646953 - 745315693151 > BB [D:\src\UIforETW\UIforETW\KeyLoggerThread.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xxast.dll)=5.77924s < 745310773910 - 745326538546 > BB [D:\src\UIforETW\UIforETW\DirectoryMonitor.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.01558s < 745326545648 - 745326588160 > BB [D:\src\UIforETW\UIforETW\DirectoryMonitor.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xxast.dll)=5.81706s < 745310918922 - 745326786697 > BB [D:\src\UIforETW\UIforETW\Settings.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.01674s < 745326793700 - 745326839369 > BB [D:\src\UIforETW\UIforETW\Settings.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xxast.dll)=5.85337s < 745310960595 - 745326927442 > BB [D:\src\UIforETW\UIforETW\Support.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xxast.dll)=5.84179s < 745310993490 - 745326928731 > BB [D:\src\UIforETW\UIforETW\UIforETW.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.01908s < 745326934942 - 745326986993 > BB [D:\src\UIforETW\UIforETW\Support.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.01887s < 745326935580 - 745326987042 > BB [D:\src\UIforETW\UIforETW\UIforETW.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xxast.dll)=5.95006s < 745310895021 - 745327125595 > BB [D:\src\UIforETW\UIforETW\ChildProcess.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.01658s < 745327132413 - 745327177636 > BB [D:\src\UIforETW\UIforETW\ChildProcess.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xxast.dll)=6.79726s < 745311193497 - 745329735063 > BB [D:\src\UIforETW\UIforETW\Utility.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.01875s < 745329742445 - 745329793603 > BB [D:\src\UIforETW\UIforETW\Utility.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xxast.dll)=8.45697s < 745311896690 - 745334965642 > BB [D:\src\UIforETW\UIforETW\UIforETWDlg.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.02320s < 745334972695 - 745335035976 > BB [D:\src\UIforETW\UIforETW\UIforETWDlg.cpp]
1>    OptRef: Total time = 0.000s
1>  Generating code
1>  Finished generating code
1>    OptRef: Total time = 0.000s
1>    OptIcf: Total time = 0.000s
1>  Pass 1: Interval #1, time = 3.015s
1>    Wait PDB close: Total time = 0.500s
1>  Pass 2: Interval #2, time = 0.578s
1>  Final: Total time = 3.593s
1>  UIforETW.vcxproj -> D:\src\UIforETW\UIforETW\..\bin\UIforETW_devrel.exe
d:\src\uiforetw\uiforetw\uiforetwdlg.cpp(284): error C6246: Local declaration of 'bNameValid' hides declaration of the same name in outer scope. For additional information, see previous declaration at line '278' of 'd:\src\uiforetw\uiforetw\uiforetwdlg.cpp'.
d:\src\uiforetw\uiforetw\uiforetwdlg.cpp(299): warning C6102: Using 'windowsDir' from failed function call at line '298'.
d:\src\uiforetw\uiforetw\uiforetwdlg.cpp(310): warning C6102: Using 'progFilesx86Dir' from failed function call at line '309'.
1>
1>Project Performance Summary:
1>    41208 ms  D:\src\UIforETW\UIforETW\UIforETW.vcxproj   1 calls
1>              41208 ms  Build                                      1 calls
1>
1>Target Performance Summary:
1>        0 ms  ComputeManifestInputsTargets               1 calls
1>        0 ms  ResolveReferences                          1 calls
1>        0 ms  SelectClCompile                            1 calls
1>        0 ms  GetResolvedWinMD                           1 calls
1>        0 ms  _Manifest                                  1 calls
1>        0 ms  _SelectedFiles                             1 calls
1>        0 ms  _PrepareForBuild                           1 calls
1>        0 ms  _Midl                                      1 calls
1>        0 ms  SelectCustomBuild                          1 calls
1>        0 ms  _ClCompile                                 1 calls
1>        0 ms  GetReferenceAssemblyPaths                  1 calls
1>        0 ms  CreateCustomManifestResourceNames          1 calls
1>        0 ms  ResolveAssemblyReferences                  1 calls
1>        0 ms  BeforeLink                                 1 calls
1>        0 ms  AfterBuildCompileEvent                     1 calls
1>        0 ms  BeforeResourceCompile                      1 calls
1>        0 ms  ComputeManifestGeneratedLinkerInputs       1 calls
1>        0 ms  AfterBuildGenerateSources                  1 calls
1>        0 ms  MakeDirsForCl                              1 calls
1>        0 ms  BuildCompileTraverse                       1 calls
1>        0 ms  BuildGenerateSources                       1 calls
1>        0 ms  GetFrameworkPaths                          1 calls
1>        0 ms  AfterResourceCompile                       1 calls
1>        0 ms  _Xsd                                       1 calls
1>        0 ms  ComputeCustomBuildOutput                   1 calls
1>        0 ms  MakeDirsForBscMake                         1 calls
1>        0 ms  ComputeLinkSwitches                        1 calls
1>        0 ms  AfterMidl                                  1 calls
1>        0 ms  MakeDirsForResourceCompile                 1 calls
1>        0 ms  ComputeLinkInputsFromProject               1 calls
1>        0 ms  _Link                                      1 calls
1>        0 ms  BuildLinkTraverse                          1 calls
1>        0 ms  ComputeRCOutputs                           1 calls
1>        0 ms  _XdcMake                                   1 calls
1>        0 ms  SelectResourceCompile                      1 calls
1>        0 ms  ExpandSDKReferences                        1 calls
1>        0 ms  _ResourceCompile                           1 calls
1>        0 ms  _PrepareForReferenceResolution             1 calls
1>        0 ms  ComputeMIDLGeneratedCompileInputs          1 calls
1>        0 ms  AfterResolveReferences                     1 calls
1>        0 ms  _BuildGenerateSourcesAction                1 calls
1>        0 ms  MakeDirsForMidl                            1 calls
1>        0 ms  PreBuildEvent                              1 calls
1>        0 ms  ComputeReferenceCLInput                    1 calls
1>        0 ms  DoLinkOutputFilesMatch                     1 calls
1>        0 ms  BeforeResolveReferences                    1 calls
1>        0 ms  ComputeCLCompileGeneratedSbrFiles          1 calls
1>        0 ms  ResolveSDKReferences                       1 calls
1>        0 ms  _ALink                                     1 calls
1>        0 ms  BeforeClCompile                            1 calls
1>        0 ms  ComputeCLGeneratedLinkInputs               1 calls
1>        0 ms  AfterBuildGenerateSourcesEvent             1 calls
1>        0 ms  PrepareResourceNames                       1 calls
1>        0 ms  AfterLink                                  1 calls
1>        0 ms  _BscMake                                   1 calls
1>        0 ms  ComputeRCGeneratedLinkInputs               1 calls
1>        0 ms  MakeDirsForXdcMake                         1 calls
1>        0 ms  BeforeBuildGenerateSources                 1 calls
1>        0 ms  AfterClCompile                             1 calls
1>        0 ms  ResolvedXDCMake                            1 calls
1>        0 ms  PlatformPrepareForBuild                    1 calls
1>        0 ms  BuildCompile                               1 calls
1>        0 ms  GetInstalledSDKLocations                   1 calls
1>        0 ms  RegisterOutput                             1 calls
1>        0 ms  _BuildCompileAction                        1 calls
1>        0 ms  BuildGenerateSourcesTraverse               1 calls
1>        0 ms  AssignProjectConfiguration                 1 calls
1>        0 ms  _SplitProjectReferencesByFileExistence     1 calls
1>        1 ms  ComputeLinkImportLibraryOutputsForClean    1 calls
1>        1 ms  ResolveProjectReferences                   1 calls
1>        1 ms  AssignTargetPaths                          1 calls
1>        1 ms  SetBuildDefaultEnvironmentVariables        1 calls
1>        1 ms  ComputeLegacyManifestEmbedding             1 calls
1>        1 ms  MakeDirsForLink                            1 calls
1>        1 ms  SplitResourcesByCulture                    1 calls
1>        1 ms  PreLinkEvent                               1 calls
1>        1 ms  ComputeCLCompileGeneratedXDCFiles          1 calls
1>        1 ms  ComputeCLOutputs                           1 calls
1>        1 ms  ComputeCLInputPDBName                      1 calls
1>        2 ms  WarnCompileDuplicatedFilename              1 calls
1>        3 ms  _CheckForInvalidConfigurationAndPlatform   1 calls
1>        3 ms  PrepareForBuild                            1 calls
1>        5 ms  InitializeBuildStatus                      1 calls
1>        5 ms  RunMergeNativeCodeAnalysis                 1 calls
1>        7 ms  SetCABuildNativeEnvironmentVariables       1 calls
1>        8 ms  RunNativeCodeAnalysis                      1 calls
1>      172 ms  ResourceCompile                            1 calls
1>     3780 ms  Link                                       1 calls
1>    37211 ms  ClCompile                                  1 calls
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========





1>------ Build started: Project: UIforETW, Configuration: Release Win32 ------
1>  stdafx.cpp
1>  _WIN32_WINNT not defined. Defaulting to _WIN32_WINNT_MAXVER (see WinSDKVer.h)
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=2.73050s < 745480341607 - 745487789870 > BB [D:\src\UIforETW\UIforETW\stdafx.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.08234s < 745487796920 - 745488021516 > BB [D:\src\UIforETW\UIforETW\stdafx.cpp]
1>  ChildProcess.cpp
1>  DirectoryMonitor.cpp
1>  KeyLoggerThread.cpp
1>  Settings.cpp
1>  Support.cpp
1>  Utility.cpp
1>  UIforETW.cpp
1>  UIforETWDlg.cpp
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.47294s < 745488720158 - 745490010235 > BB [D:\src\UIforETW\UIforETW\KeyLoggerThread.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.01694s < 745490017411 - 745490063631 > BB [D:\src\UIforETW\UIforETW\KeyLoggerThread.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.60821s < 745488689102 - 745490348171 > BB [D:\src\UIforETW\UIforETW\DirectoryMonitor.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.01560s < 745490354917 - 745490397479 > BB [D:\src\UIforETW\UIforETW\DirectoryMonitor.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.59258s < 745488885283 - 745490501733 > BB [D:\src\UIforETW\UIforETW\Support.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.66839s < 745488684785 - 745490508027 > BB [D:\src\UIforETW\UIforETW\ChildProcess.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.59921s < 745488892347 - 745490526873 > BB [D:\src\UIforETW\UIforETW\UIforETW.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.66304s < 745488720553 - 745490529194 > BB [D:\src\UIforETW\UIforETW\Settings.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.02177s < 745490508861 - 745490568244 > BB [D:\src\UIforETW\UIforETW\Support.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.02193s < 745490515362 - 745490575180 > BB [D:\src\UIforETW\UIforETW\ChildProcess.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.02193s < 745490534162 - 745490593973 > BB [D:\src\UIforETW\UIforETW\UIforETW.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.02181s < 745490536309 - 745490595815 > BB [D:\src\UIforETW\UIforETW\Settings.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.67378s < 745488885517 - 745490723458 > BB [D:\src\UIforETW\UIforETW\Utility.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.02473s < 745490729849 - 745490797321 > BB [D:\src\UIforETW\UIforETW\Utility.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c1xx.dll)=0.94067s < 745488893201 - 745491459168 > BB [D:\src\UIforETW\UIforETW\UIforETWDlg.cpp]
1>  time(C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\c2.dll)=0.02329s < 745491466229 - 745491529767 > BB [D:\src\UIforETW\UIforETW\UIforETWDlg.cpp]
1>    OptRef: Total time = 0.000s
1>  Generating code
1>  Finished generating code
1>    OptRef: Total time = 0.000s
1>    OptIcf: Total time = 0.015s
1>  Pass 1: Interval #1, time = 2.921s
1>    Wait PDB close: Total time = 0.453s
1>  Pass 2: Interval #2, time = 0.500s
1>  Final: Total time = 3.421s
1>  UIforETW.vcxproj -> D:\src\UIforETW\UIforETW\..\bin\UIforETW_devrel.exe
1>
1>Project Performance Summary:
1>     8097 ms  D:\src\UIforETW\UIforETW\UIforETW.vcxproj   1 calls
1>               8097 ms  Build                                      1 calls
1>
1>Target Performance Summary:
1>        0 ms  AfterBuild                                 1 calls
1>        0 ms  ComputeCLCompileGeneratedXDCFiles          1 calls
1>        0 ms  ComputeManifestGeneratedLinkerInputs       1 calls
1>        0 ms  ResolveReferences                          1 calls
1>        0 ms  SelectClCompile                            1 calls
1>        0 ms  GetCopyToOutputDirectoryXamlAppDefs        1 calls
1>        0 ms  _Manifest                                  1 calls
1>        0 ms  _SelectedFiles                             1 calls
1>        0 ms  _PrepareForBuild                           1 calls
1>        0 ms  PostBuildEvent                             1 calls
1>        0 ms  _Midl                                      1 calls
1>        0 ms  SelectCustomBuild                          1 calls
1>        0 ms  _ClCompile                                 1 calls
1>        0 ms  CreateCustomManifestResourceNames          1 calls
1>        0 ms  SetBuildDefaultEnvironmentVariables        1 calls
1>        0 ms  ResolveAssemblyReferences                  1 calls
1>        0 ms  BeforeLink                                 1 calls
1>        0 ms  ComputeCLInputPDBName                      1 calls
1>        0 ms  AfterBuildCompileEvent                     1 calls
1>        0 ms  GetCopyToOutputDirectoryItems              1 calls
1>        0 ms  AfterBuildGenerateSources                  1 calls
1>        0 ms  _BuildLinkAction                           1 calls
1>        0 ms  BuildCompileTraverse                       1 calls
1>        0 ms  SelectResourceCompile                      1 calls
1>        0 ms  BuildGenerateSources                       1 calls
1>        0 ms  _CopySourceItemsToOutputDirectory          1 calls
1>        0 ms  ComputeLinkImportLibraryOutputsForClean    1 calls
1>        0 ms  GetFrameworkPaths                          1 calls
1>        0 ms  AfterResourceCompile                       1 calls
1>        0 ms  _Xsd                                       1 calls
1>        0 ms  ComputeCustomBuildOutput                   1 calls
1>        0 ms  MakeDirsForBscMake                         1 calls
1>        0 ms  ComputeLinkSwitches                        1 calls
1>        0 ms  MakeDirsForResourceCompile                 1 calls
1>        0 ms  _ResourceCompile                           1 calls
1>        0 ms  ComputeLinkInputsFromProject               1 calls
1>        0 ms  Build                                      1 calls
1>        0 ms  _Link                                      1 calls
1>        0 ms  BuildLinkTraverse                          1 calls
1>        0 ms  ComputeRCOutputs                           1 calls
1>        0 ms  _XdcMake                                   1 calls
1>        0 ms  CreateSatelliteAssemblies                  1 calls
1>        0 ms  CopyFilesToOutputDirectory                 1 calls
1>        0 ms  ExpandSDKReferences                        1 calls
1>        0 ms  BeforeResourceCompile                      1 calls
1>        0 ms  ComputeMIDLGeneratedCompileInputs          1 calls
1>        0 ms  PreLinkEvent                               1 calls
1>        0 ms  _BuildGenerateSourcesAction                1 calls
1>        0 ms  RegisterOutput                             1 calls
1>        0 ms  AfterLink                                  1 calls
1>        0 ms  PrepareResourceNames                       1 calls
1>        0 ms  AfterBuildGenerateSourcesEvent             1 calls
1>        0 ms  BeforeClCompile                            1 calls
1>        0 ms  ComputeCLOutputs                           1 calls
1>        0 ms  AfterResolveReferences                     1 calls
1>        0 ms  AfterMidl                                  1 calls
1>        0 ms  BeforeResolveReferences                    1 calls
1>        0 ms  DoLinkOutputFilesMatch                     1 calls
1>        0 ms  ComputeReferenceCLInput                    1 calls
1>        0 ms  _Appverifier                               1 calls
1>        0 ms  PrepareForRun                              1 calls
1>        0 ms  PreBuildEvent                              1 calls
1>        0 ms  BuildLink                                  1 calls
1>        0 ms  MakeDirsForMidl                            1 calls
1>        0 ms  SplitResourcesByCulture                    1 calls
1>        0 ms  BuildCompile                               1 calls
1>        0 ms  _Deploy                                    1 calls
1>        0 ms  _PrepareForReferenceResolution             1 calls
1>        0 ms  _SplitProjectReferencesByFileExistence     1 calls
1>        0 ms  ResolveProjectReferences                   1 calls
1>        0 ms  BeforeBuildGenerateSources                 1 calls
1>        0 ms  AfterClCompile                             1 calls
1>        0 ms  ComputeRCGeneratedLinkInputs               1 calls
1>        0 ms  ComputeCLGeneratedLinkInputs               1 calls
1>        0 ms  PlatformPrepareForBuild                    1 calls
1>        0 ms  ResolveSDKReferences                       1 calls
1>        0 ms  MakeDirsForXdcMake                         1 calls
1>        0 ms  GetInstalledSDKLocations                   1 calls
1>        0 ms  _BuildCompileAction                        1 calls
1>        0 ms  ComputeCLCompileGeneratedSbrFiles          1 calls
1>        0 ms  _ALink                                     1 calls
1>        0 ms  _BscMake                                   1 calls
1>        1 ms  ComputeLegacyManifestEmbedding             1 calls
1>        1 ms  MakeDirsForCl                              1 calls
1>        1 ms  ResolvedXDCMake                            1 calls
1>        1 ms  MakeDirsForLink                            1 calls
1>        1 ms  GetResolvedWinMD                           1 calls
1>        1 ms  _CheckForCompileOutputs                    1 calls
1>        1 ms  BuildGenerateSourcesTraverse               1 calls
1>        1 ms  AssignTargetPaths                          1 calls
1>        1 ms  AssignProjectConfiguration                 1 calls
1>        1 ms  GetReferenceAssemblyPaths                  1 calls
1>        1 ms  ComputeManifestInputsTargets               1 calls
1>        1 ms  _GenerateSatelliteAssemblyInputs           1 calls
1>        2 ms  WarnCompileDuplicatedFilename              1 calls
1>        3 ms  InitializeBuildStatus                      1 calls
1>        3 ms  FinalizeBuildStatus                        1 calls
1>        3 ms  _CheckForInvalidConfigurationAndPlatform   1 calls
1>        3 ms  PrepareForBuild                            1 calls
1>        4 ms  SetCABuildNativeEnvironmentVariables       1 calls
1>      170 ms  ResourceCompile                            1 calls
1>     3556 ms  Link                                       1 calls
1>     4337 ms  ClCompile                                  1 calls
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by ariccio** [comment]
Ah, ok. 41 seconds is ok for me, but it's totally understandable that it isn't for others.

**Pull request merged**
