### PR TITLE
Set up GitHub task lists in the UIforETW subfolder's readme

### PR DESCRIPTION
**Pull request by ariccio**
They look pretty cool, and might also be useful.

I updated the most obviously completed tasks, I probably missed a few.

I'm not sure why part of it shows up in italic here, as it's fine from the web interface (of the UIforETW subfolder).

### CODE REVIEW

**Comment by ariccio** [comment]
Screenshot:
githubuiforetw_tasklists

**Comment by randomascii** [comment]
Interesting. Is it just so it displays better on the web page?

**Comment by ariccio** [comment]
> Interesting. Is it just so it displays better on the web page?

Yup. Pretty much. That makes it a bit easier to organize.

**Comment by randomascii** [comment]
I haven't been using that todo list since moving to github. Issues and pull
requests so far.

I made some updates -- many missing 'x' characters.

On Tue, May 12, 2015 at 10:53 PM, Alexander Riccio <notifications@github.com
> wrote:

> Interesting. Is it just so it displays better on the web page?
>
> Yup. Pretty much. That makes it a bit easier to organize.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/UIforETW/pull/32#issuecomment-101522393>.
>



-- 
Bruce Dawson

**Pull request merged**
