### PR TITLE
Python cleanup & minor refactoring

### PR DESCRIPTION
**Pull request by ariccio**
This is a redo of Pull-Request #22 - it was easier to just manually make the changes.

I improved [style compliance](https://www.chromium.org/chromium-os/python-style-guidelines) of the Python scripts, and also improved the Python 2.x/3.x cross-compatibility. Running pylint helps!

Removed a few usages of depreciated functions, `os.popen` & `has_key`, and replaced with modern/pythonic alternatives.

For now, I couldn't remove a few globals from XperfProcessParentage.py. Grr.

This should improve readability.

### CODE REVIEW

**Comment by randomascii** [comment]
I merged this pull request on the command line. I'm not sure why it shows up as unmerged here. Closing as merged.

**Comment by ariccio** [comment]
That is really weird.....maybe if you touch a file (or whatever triggers a "change" that git notices) and commit that, it'll work.

It isn't showing up in the compare screen either:
github_merged_via_command_line_not_updated

**Comment by randomascii** [comment]
But I do see the changes on github, which is what really matters. Do you
see them?

On Sun, May 3, 2015 at 11:19 PM, Alexander Riccio <notifications@github.com>
wrote:

> That is really weird.....maybe if you touch a file (or whatever triggers a
> "change" that git notices) and commit that, it'll work.
>
> It isn't showing up in the compare screen either:
> [image: github_merged_via_command_line_not_updated]
> <https://cloud.githubusercontent.com/assets/2142308/7449423/f64dd532-f203-11e4-8394-8edcbdf66e33.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/UIforETW/pull/23#issuecomment-98595771>.
>



-- 
Bruce Dawson

**Comment by ariccio** [comment]
Yeah, I do, and successfully merged them into master & dev, but I'm just a tad bit nervous about deleting the now-defunct branch.

I'll probably just think "hell with it" to myself tomorrow and delete it anyways.

**Pull request closed without merging**
